// import { Inter } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Sidebar from "@/components/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar/>
//         <div className="flex ">
//           <Sidebar/>
//         {children}
//         </div></body>
//     </html>
//   );
// }
// layout.jsx
// 'use client'
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';
import {AppProvider}  from './AppContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      </head>
      <body className={inter.className}>
        <AppProvider>
          <Navbar />
          <div className="flex">
            <Sidebar />
            {children}
          </div>
        </AppProvider>
      </body>
    </html>
  );
}

